### ISSUE TITLE
Nitpick Collection

### ISSUE THREAD

**Issue by Steav005** [aeronautical-informatics/apex-linux#38]
https://github.com/aeronautical-informatics/apex-linux/blob/76dee04a764113fc9a2eae371972faeac598556b/core/src/cgroup.rs#L172-L179 Use [for range](https://doc.rust-lang.org/rust-by-example/flow_control/for.html) instead

https://github.com/aeronautical-informatics/apex-linux/blob/76dee04a764113fc9a2eae371972faeac598556b/core/src/cgroup.rs#L88-L91 Return error instead of unwrapping

https://github.com/aeronautical-informatics/apex-linux/blob/76dee04a764113fc9a2eae371972faeac598556b/partition/src/apex.rs#L155-L159 Use [ok_or_else](https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or_else) with `?` instead

**Comment by emilengler** [comment]
I doubt that the latter one is what you want, because `read` is of type `Result<T, E>` and not `Option<T>`
